// modules
import Head from 'next/head'

// components
import HomeMain from '../src/components/HomeMain'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeMain />
      <footer></footer>
     
    </div>
  )
}
